"""Structured contracts for Asumi Tarot 2.0 readings."""

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class TarotCardInsight(BaseModel):
    position_id: str = Field(default="", description="Stable/short position identifier or position title.")
    card_id: str = Field(default="", description="Card id supplied by the Tarot engine.")
    card_name: str = Field(default="", description="Human-readable card name from the supplied spread.")
    insight: str = Field(default="", description="One concise contextual insight for this card/position.")


class TarotConnection(BaseModel):
    card_ids: List[str] = Field(default_factory=list, description="Two or more supplied card ids participating in this relationship.")
    meaning: str = Field(default="", description="Natural-language explanation of reinforcement, conflict, progression or transition.")


class TarotKeyCard(BaseModel):
    card_id: str = Field(default="", description="The supplied card id carrying the strongest thematic weight.")
    card_name: str = Field(default="", description="Human-readable supplied card name.")
    reason: str = Field(default="", description="Why this card is central to this particular reading.")


class TarotClarifierTarget(BaseModel):
    position_id: str = Field(default="", description="Existing spread position worth clarifying.")
    reason: str = Field(default="", description="Why this position remains ambiguous or important.")


class TarotAIResponseSchema(BaseModel):
    """Gemini response schema for Tarot 2.0.

    The model returns meaning as structured data; Discord formatting is generated by
    application code so future UI milestones can reuse the same reading safely.
    """

    is_valid: bool = Field(
        default=True,
        description="False only when the reading request crosses privacy/safety boundaries.",
    )
    topic_tag: str = Field(
        default="general",
        description="One of career, love, finance, health, study, creative, decision, general.",
    )
    mood_tag: str = Field(
        default="Cân bằng & Tĩnh tại",
        description="Short Vietnamese mood/vibe tag, descriptive rather than diagnostic.",
    )
    headline: str = Field(
        default="",
        description="Natural Vietnamese reading headline, ideally under 15 words.",
    )
    core_message: str = Field(
        default="",
        description="2-3 natural sentences stating the central pattern of the spread.",
    )
    card_insights: List[TarotCardInsight] = Field(
        default_factory=list,
        description="Concise contextual insights tied only to cards/positions supplied by the engine.",
    )
    connections: List[TarotConnection] = Field(
        default_factory=list,
        description="The most important relationships between supplied cards; prefer synthesis over per-card summaries.",
    )
    dominant_theme: str = Field(
        default="",
        description="Short synthesis of the dominant pattern, if one is clearly supported.",
    )
    key_card: TarotKeyCard = Field(
        default_factory=TarotKeyCard,
        description="The most thematically important supplied card and why.",
    )
    practical_takeaway: List[str] = Field(
        default_factory=list,
        description="1-3 grounded actions or reflection prompts; no deterministic commands.",
    )
    uncertainty: str = Field(
        default="",
        description="What the spread cannot establish with confidence or still depends on user choice/context.",
    )
    suggested_clarifier_targets: List[TarotClarifierTarget] = Field(
        default_factory=list,
        description="0-2 existing positions that would benefit from a clarifier later; do not draw new cards.",
    )
    journey_tags: List[str] = Field(
        default_factory=list,
        description="0-4 short neutral tags useful for future Tarot Journey analytics.",
    )
    refusal_message: str = Field(
        default="",
        description="Short user-facing refusal/redirection when is_valid=false; otherwise empty.",
    )


class TarotClarifierAIResponseSchema(BaseModel):
    """Structured one-card clarifier interpretation.

    The clarifier supplements one existing position. It must not rewrite or reroll the
    original reading.
    """

    relationship: str = Field(
        default="",
        description="How the clarifier relates to the selected target card/position.",
    )
    clarity: str = Field(
        default="",
        description="What becomes clearer after adding this clarifier.",
    )
    effect: str = Field(
        default="",
        description="Short label/phrase: strengthens, softens, redirects or mixes the original interpretation.",
    )
    practical_implication: str = Field(
        default="",
        description="Grounded implication or reflection step based on target + clarifier.",
    )
    uncertainty: str = Field(
        default="",
        description="What remains uncertain after the clarifier.",
    )


class TarotClarifierResult(BaseModel):
    relationship: str = ""
    clarity: str = ""
    effect: str = ""
    practical_implication: str = ""
    uncertainty: str = ""
    full_reading: str = ""



class TarotReadingResult(BaseModel):
    """Normalized application result while legacy callers still consume a tuple."""

    full_reading: str = ""
    topic_tag: str = "general"
    mood_tag: str = "Cân bằng & Tĩnh tại"
    headline: str = ""
    is_valid: bool = True

    core_message: str = ""
    dominant_theme: str = ""
    card_insights: List[TarotCardInsight] = Field(default_factory=list)
    connections: List[TarotConnection] = Field(default_factory=list)
    key_card: TarotKeyCard = Field(default_factory=TarotKeyCard)
    practical_takeaway: List[str] = Field(default_factory=list)
    uncertainty: str = ""
    suggested_clarifier_targets: List[TarotClarifierTarget] = Field(default_factory=list)
    journey_tags: List[str] = Field(default_factory=list)

    def as_legacy_tuple(self) -> tuple[str, str, str, str, bool]:
        return (
            self.full_reading,
            self.topic_tag,
            self.mood_tag,
            self.headline,
            self.is_valid,
        )
